### ISSUE TITLE
Gateway server initialize

### ISSUE THREAD

**Issue by ignisilva** [ignisilva/RPM#2]
## Description 

Create gateway server and initialize

## Tasks

- [x] Create gateway server
- [x] Setup and apply dotenv for using env
- [x] Setup and apply joi for check env elements
- [x] Setup and apply cross-env for Dev

**Comment by ignisilva** [comment]
resolve #2
