### ISSUE TITLE
Database initialize

### ISSUE THREAD

**Issue by ignisilva** [ignisilva/RPM#3]
## Description

Make Database for gateway 

gateway need user table for authentication

## Tasks

- [x] make user in postgresql for gateway server
- [x] Connect db with server using typescript
- [x] Connection test (sample data insert)

**Comment by ignisilva** [comment]
resolve #3
